### ISSUE TITLE
Cannot run Prodigy using `poetry run prodigy`

### ISSUE THREAD

**Issue by fzaiser** [LKlinke/Prodigy#33]
It would be easier for scripting if one could run Prodigy directly, without entering `poetry shell` first (for example if one has another Python project with a different virtual env). If I try this, I get:
```
$ poetry run prodigy pgfexamples/inference/burgler_alarm.pgcl 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/REDACTED/.cache/pypoetry/virtualenvs/prodigy-mwvi2G9N-py3.10/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/REDACTED/.cache/pypoetry/virtualenvs/prodigy-mwvi2G9N-py3.10/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/REDACTED/.cache/pypoetry/virtualenvs/prodigy-mwvi2G9N-py3.10/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/REDACTED/.cache/pypoetry/virtualenvs/prodigy-mwvi2G9N-py3.10/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/REDACTED/.cache/pypoetry/virtualenvs/prodigy-mwvi2G9N-py3.10/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/REDACTED/Prodigy/prodigy/cli.py", line 87, in main
    config = ctx.obj['CONFIG']
TypeError: 'NoneType' object is not subscriptable
```

If I try to set the engine, I get a different error:
```
$ poetry run prodigy --engine ginac pgfexamples/inference/burgler_alarm.pgcl 
Usage: prodigy [OPTIONS] PROGRAM_FILE [INPUT_DIST]
Try 'prodigy --help' for help.

Error: no such option: --engine
```

I understand if fixing this is not a priority, I just wanted to let you know that it would make using Prodigy easier. :-)

**Comment by fzaiser** [comment]
As a workaround, I added the following to `pyproject.toml`:
```
[tool.poetry.scripts]
cli = "prodigy.cli:cli"
```

Then I can run it via `poetry run cli --engine ginac main pgfexamples/inference/burgler_alarm.pgcl `. But I don't know much about Python and poetry, so there's probably a better solution.

**Comment by LKlinke** [comment]
will be fixed in next master branch update.
